export const NEW_SHOPPING_ITEM = 'NEW_SHOP_ITEM';
export const TOGGLE_COMPLETED = 'TOGGLE_COMPLETED';
export const DELETE_SHOPPING_ITEM = 'DELETE_SHOPPING_ITEM';
export const CANCEL_SHOPPING_ITEM = 'CANCEL_SHOPPING_ITEM';
export const EDIT_SHOPPING_ITEM = 'EDIT_SHOPPING_ITEM';
export const UPDATA_SHOPPING_ITEM = 'UPDATA_SHOPPING_ITEM';
